# Configuración de ramas protegidas
branches:
  - name: main
    # Requiere revisiones de aprobación
    required_pull_request_reviews:
      required_approving_review_count: 1
      require_code_owner_reviews: true
      dismiss_stale_reviews: true
    # Restricciones de push
    restrictions: null
    # Requisitos de estado
    required_status_checks:
      strict: true
      contexts:
        - "lint"
        - "test"
    enforce_admins: false
    allow_force_pushes: false
    allow_deletions: false

  - name: develop
    # Requiere revisión de PR
    required_pull_request_reviews:
      required_approving_review_count: 1
    required_status_checks:
      strict: true
      contexts:
        - "lint"
        - "test"
    enforce_admins: false
    allow_force_pushes: false
    allow_deletions: false
